### ISSUE TITLE
StudyDate is missing on some sessions

### ISSUE THREAD

**Issue by spikelynch** [Sydney-Informatics-Hub/xnat-uploader#109]
Have reproduced this with 0522 on both DJ and ML's machine, uploading to both the production XNAT and a local Dockerised version

StudyDate is empty on the subject page next to the experiment. The scans upload OK and can be downloaded, but the OHIF viewer doesn't launch, complaining about metadata

**Comment by spikelynch** [comment]
This seems to be being triggered by a single DICOM which is labelled "doseinfo" and which probably should be being excluded (not a scan, PID)

**Comment by spikelynch** [comment]
Have added a test for ImageType which rejects DOSE_INFO but this isn't getting all of them (see 0712 on the AILDR server)

**Comment by spikelynch** [comment]
Found the error on the server logs in /data/xnat/home/logs/restlet.log

```
2024-04-12 02:30:47,533 [http-nio-8080-exec-8] ERROR org.nrg.xnat.restlet.resources.SubjAssessmentAbst -
java.lang.Exception: Modification of scan modality (xnat:ctScanData to xnat:scScanData) not supported.
        at org.nrg.xnat.restlet.actions.PullSessionDataFromHeaders.call(PullSessionDataFromHeaders.java:125)
        at org.nrg.xnat.restlet.resources.SubjAssessmentResource.handlePut(SubjAssessmentResource.java:510)
        at org.restlet.Finder.handle(Finder.java:359)
        at org.restlet.Filter.doHandle(Filter.java:150)

```

**Comment by spikelynch** [comment]
Have changed the script so that it skips DOSE_INFO automatically
